canonical: https://gematik.de/fhir/isik
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: 4.0.0-rc
dependencies:
  de.basisprofil.r4: 1.5.0-ballot2
  hl7.fhir.r4.core: 4.0.1
