canonical: https://gematik.de/fhir/isik
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: 4.0.0
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.gematik.isik-basismodul: 4.0.0
  de.gematik.isik-medikation: 4.0.0
